CREATE TABLE EMP_RECORDS (
    ENO   VARCHAR2(4) PRIMARY KEY,
    ENAME VARCHAR2(50),
    SAL   NUMBER(10,2)
);

CREATE SEQUENCE EMP_SEQ
START WITH 1
INCREMENT BY 1
MAXVALUE 999
NOCYCLE;

CREATE OR REPLACE TRIGGER EMP_ENO_TRG
BEFORE INSERT ON EMP_RECORDS
FOR EACH ROW
DECLARE
    V_ENO NUMBER;
BEGIN
    SELECT EMP_SEQ.NEXTVAL
    INTO V_ENO
    FROM DUAL;

    :NEW.ENO := 'E' || LPAD(V_ENO, 3, '0');
END;
/