/* Write a PL/SQL block that find 
	2.Area of Rectangle(length*width)
*/

SET SERVEROUTPUT ON
SET VERIFY OFF
SET FEEDBACK OFF

DECLARE
	LENGTH NUMBER(5);
	WIDTH NUMBER(5);
	AREA NUMBER(9,2);

BEGIN
	LENGTH:=&LENGTH;
	WIDTH:=&WIDTH;
	AREA:=LENGTH*WIDTH;
	DBMS_OUTPUT.PUT_LINE('The value of Area is : ' || AREA);

END;
/
SET SERVEROUTPUT OFF
SET VERIFY ON
SET FEEDBACK ON