/*
Create a STUDENT table and write a PL/SQL block that accepts Roll 
Number and: 
 Calculates Total  
 Percentage  
 Assigns Grade  
 Displays Pass/Fail status (Pass if all subjects ≥35).
*/

CREATE TABLE STUDENT
(
    ROLLNO NUMBER(5),
    STUDENT_NAME VARCHAR2(20),
    SUB1 NUMBER(7),
    SUB2 NUMBER(7),
    SUB3 NUMBER(7),
    SUB4 NUMBER(7),
    SUB5 NUMBER(7),
    TOTAL NUMBER(7),
    PERCENTAGE NUMBER(7,2),
    GRADE VARCHAR2(20),
    FINAL_STATUS VARCHAR2(20)
);

INSERT INTO STUDENT
(ROLLNO, STUDENT_NAME, SUB1, SUB2, SUB3, SUB4, SUB5)
VALUES
(1, 'KUNJAL', 80, 75, 90, 85, 70);

INSERT INTO STUDENT
(ROLLNO, STUDENT_NAME, SUB1, SUB2, SUB3, SUB4, SUB5)
VALUES
(2, 'DEV', 90,80, 90, 85, 75);

INSERT INTO STUDENT
(ROLLNO, STUDENT_NAME, SUB1, SUB2, SUB3, SUB4, SUB5)
VALUES
(3, 'MOIN', 30, 25, 0, 55, 54);


SET SERVEROUTPUT ON
SET VERIFY OFF
SET FEEDBACK OFF


DECLARE
	V_ROLLNO	RESULT.ROLLNO%TYPE;
	V_NAME		RESULT.NAME%TYPE;
	V_SUB1		RESULT.SUB1%TYPE;
	V_SUB2		RESULT.SUB2%TYPE;
	V_SUB3		RESULT.SUB3%TYPE;
	V_SUB4		RESULT.SUB4%TYPE;
	V_SUB5		RESULT.SUB5%TYPE;

	V_TOTAL		RESULT.TOTAL%TYPE;
	V_PER		RESULT.PER%TYPE;
	V_GRADE		RESULT.GRADE%TYPE;
	
BEGIN
	V_ROLLNO:=&V_ROLLNO;
	
	SELECT ROLLNO,NAME,SUB1,SUB2,SUB3,SUB4,SUB5 INTO V_ROLLNO,V_NAME,V_SUB1,V_SUB2,V_SUB3,V_SUB4,V_SUB5 FROM RESULT WHERE ROLLNO=V_ROLLNO;

	V_TOTAL:=V_SUB1+V_SUB2+V_SUB3+V_SUB4+V_SUB5;
	V_PER:=V_TOTAL/5;
	
	IF (V_PER>=70) THEN
		V_GRADE:='DISTINCTION';
	ELSIF (V_PER>=60 AND V_PER<70) THEN
		V_GRADE:='FIRST CLASS';
	ELSIF (V_PER>=50 AND V_PER<60) THEN
		V_GRADE:='SECOND CLASS';
	ELSIF (V_PER>=40 AND V_PER<50) THEN
		V_GRADE:='PASS CLASS';
	ELSE
		V_GRADE:='FAIL';
	END IF;
	
	DBMS_OUTPUT.PUT_LINE('--------------------RESULT--------------------');
	DBMS_OUTPUT.PUT_LINE('ROLLNO: - '||V_ROLLNO);
	DBMS_OUTPUT.PUT_LINE('NAME: - '||V_NAME);
	DBMS_OUTPUT.PUT_LINE('MARKS OF SUB1: - '||V_SUB1);
	DBMS_OUTPUT.PUT_LINE('MARKS OF SUB2: - '||V_SUB2);
	DBMS_OUTPUT.PUT_LINE('MARKS OF SUB3: - '||V_SUB3);
	DBMS_OUTPUT.PUT_LINE('MARKS OF SUB4: - '||V_SUB4);
	DBMS_OUTPUT.PUT_LINE('MARKS OF SUB5: - '||V_SUB5);
	DBMS_OUTPUT.PUT_LINE('----------------------------');
	DBMS_OUTPUT.PUT_LINE('TOTAL MARKS: - '||V_TOTAL);
	DBMS_OUTPUT.PUT_LINE('PERCENTAGE %: - '||V_PER);
	DBMS_OUTPUT.PUT_LINE('FINAL GRADE: - '||V_GRADE);
	DBMS_OUTPUT.PUT_LINE('----------------------------');
	
	UPDATE RESULT SET TOTAL=V_TOTAL, PER=V_PER, GRADE=V_GRADE WHERE ROLLNO=V_ROLLNO;
	DBMS_OUTPUT.PUT_LINE('Result is updated for rollno: -'||V_ROLLNO);
	
EXCEPTION
	WHEN NO_DATA_FOUND THEN
		DBMS_OUTPUT.PUT_LINE('The student with provided rollno does not exist enter proper rollno');

END;
/
SET SERVEROUTPUT OFF
SET VERIFY ON
SET FEEDBACK ON

